steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'git@github.com:lokinegalur/flask_crud.git'] 
- name: 'google/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['cp', '-r', 'flask_crud', 'gs://tf_test_bucket1']
  dir: 'flask_crud'  
